import type { Metadata } from "next";

import MainHeader from "@/components/header/main-header";

import "../globals.css";

export const metadata: Metadata = {
  title: "Daily News",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div id="page">
          <MainHeader />
          {children}
        </div>
      </body>
    </html>
  );
}
